# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
  repository_dispatch:
    types: [ build ]



# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2-beta
        with:
            Version: 12

    # Runs a set of commands using the runners shell
      - name: yarn actions (yaml)
        uses: sergioramos/yarn-actions@v6
        with:
          cmd: install #installing yarn package
          
    # Installing Gatsby to make build 
  #    - name: Installing Gatsby
   #     uses: enriikke/gatsby-gh-pages-action@v2.1.1
    #    with:
      #    cmd: gatsby build
      
    
      - name: Build with yarn
        run: yarn build
        env:
          CONTENTFUL_ACCESS_TOKEN: ${{ secrets.CONTENTFUL_ACCESS_TOKEN }}
          CONTENTFUL_SPACE_ID: ${{ secrets.CONTENTFUL_SPACE_ID }}
      
    
      - name: Installing surge
        run: npm install -g surge
        
      - name: Deploying surge
        run: surge ./public http://gatsby-blogsite-adeelmalik.surge.sh/ --token ${{ secrets.SURGE_TOKEN }}
      
